[project]
name = "ansible_home"
version = "0.1.0"
description = ""
authors = [
    {name = "David Snider",email = "david@davidsnider.org"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "ansible (>=11.5.0,<12.0.0)",
    "hvac (>=2.3.0,<3.0.0)",
    "pulumi-github (>=6.7.3,<7.0.0)",
    "pulumi (>=3.190.0,<4.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
detect-secrets = "^1.5.0"
