---
- name: Converge Linux-specific test
  hosts: localhost_linux
  become: true
  gather_facts: true
  vars:
    ansible_user_shell: /bin/bash

  pre_tasks:
    - name: Update apt cache (Ubuntu/Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install Python pip
      ansible.builtin.package:
        name:
          - python3-pip
          - curl
          - git
          - gpg
        state: present

    - name: Create test user home directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME | default('/root') }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user_id }}"

  tasks:
    # Run a subset of basic tasks for testing
    - name: Ensure ~/code directory exists
      ansible.builtin.file:
        path: /root/code
        state: directory
        mode: "0755"

    - name: Configure git user name
      community.general.git_config:
        name: user.name
        value: David Snider
        scope: global

    - name: Configure git user email
      community.general.git_config:
        name: user.email
        value: david@davidsnider.org
        scope: global

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: "0700"

    - name: Ensure ~/.local/bin directory exists
      ansible.builtin.file:
        path: /root/.local/bin
        state: directory
        mode: "0755"
