---
- name: Converge Linux-specific test
  hosts: localhost_linux
  become: true
  gather_facts: true
  vars:
    ansible_user_shell: /bin/bash

  pre_tasks:
    - name: Update apt cache (Ubuntu/Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install Python pip
      ansible.builtin.package:
        name:
          - python3-pip
          - curl
          - git
          - gpg
        state: present

    - name: Create test user home directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME | default('/root') }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user_id }}"

  tasks:
    # Include the full Linux tasks to properly test 1Password security features
    - name: Include Linux-specific tasks
      ansible.builtin.include_tasks: ../../tasks/local-linux.yml
