# GitHub repository management tasks
- name: Configure repository settings
  community.general.github_repo:
    token: "{{ github_token }}"
    organization: "{{ github_owner }}"
    repo: "{{ github_repository }}"
    name: "{{ github_repository }}"
    description: "{{ github_repository_settings.description }}"
    homepage: "{{ github_repository_settings.homepage }}"
    private: "{{ github_repository_settings.private }}"
    has_issues: "{{ github_repository_settings.has_issues }}"
    has_projects: "{{ github_repository_settings.has_projects }}"
    has_wiki: "{{ github_repository_settings.has_wiki }}"
    allow_merge_commit: "{{ github_repository_settings.allow_merge_commit }}"
    allow_squash_merge: "{{ github_repository_settings.allow_squash_merge }}"
    allow_rebase_merge: "{{ github_repository_settings.allow_rebase_merge }}"
    allow_auto_merge: "{{ github_repository_settings.allow_auto_merge }}"
    delete_branch_on_merge: "{{ github_repository_settings.delete_branch_on_merge }}"
    state: present

- name: Enable vulnerability alerts
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ github_owner }}/{{ github_repository }}/vulnerability-alerts"
    method: PUT
    headers:
      Authorization: "token {{ github_token }}"
      Accept: "application/vnd.github.dorian-preview+json"
    status_code: [204, 409]  # 409 means already enabled
  when: github_repository_settings.vulnerability_alerts

- name: Enable secret scanning
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ github_owner }}/{{ github_repository }}"
    method: PATCH
    headers:
      Authorization: "token {{ github_token }}"
      Accept: "application/vnd.github+json"
    body_format: json
    body:
      security_and_analysis:
        secret_scanning:
          status: "{{ 'enabled' if github_security_settings.enable_secret_scanning else 'disabled' }}"
        secret_scanning_push_protection:
          status: "{{ 'enabled' if github_security_settings.enable_secret_scanning_push_protection else 'disabled' }}"
    status_code: [200]
  when: github_security_settings.enable_secret_scanning or github_security_settings.enable_secret_scanning_push_protection

- name: Enable automated security fixes
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ github_owner }}/{{ github_repository }}/automated-security-fixes"
    method: PUT
    headers:
      Authorization: "token {{ github_token }}"
      Accept: "application/vnd.github.london-preview+json"
    status_code: [204, 409]  # 409 means already enabled
  when: github_security_settings.enable_automated_security_fixes

- name: Configure branch protection
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ github_owner }}/{{ github_repository }}/branches/{{ github_branch_protection.branch }}/protection"
    method: PUT
    headers:
      Authorization: "token {{ github_token }}"
      Accept: "application/vnd.github+json"
    body_format: json
    body:
      required_status_checks:
        strict: "{{ github_branch_protection.required_status_checks.strict }}"
        contexts: "{{ github_branch_protection.required_status_checks.contexts }}"
      enforce_admins: "{{ github_branch_protection.enforce_admins }}"
      required_pull_request_reviews:
        required_approving_review_count: "{{ github_branch_protection.required_pull_request_reviews.required_approving_review_count }}"
        dismiss_stale_reviews: "{{ github_branch_protection.required_pull_request_reviews.dismiss_stale_reviews }}"
        require_code_owner_reviews: "{{ github_branch_protection.required_pull_request_reviews.require_code_owner_reviews }}"
        restrict_dismissals: "{{ github_branch_protection.required_pull_request_reviews.restrict_dismissals }}"
      restrictions:
        users: "{{ github_branch_protection.restrictions.push }}"
        teams: []
        apps: "{{ github_branch_protection.restrictions.apps }}"
      allow_force_pushes: "{{ github_branch_protection.allow_force_pushes }}"
      allow_deletions: "{{ github_branch_protection.allow_deletions }}"
      required_linear_history: "{{ github_branch_protection.require_linear_history }}"
      required_conversation_resolution: "{{ github_branch_protection.require_conversation_resolution }}"
    status_code: [200]
