all:
  children:
    workstations:
      children:
        local_workstations:
          hosts:
            localhost:
              ansible_connection: local
              ansible_python_interpreter: /usr/bin/python3
        networked_workstations:
          hosts:
            # Example networked workstation
            # workstation1:
            #   ansible_host: 192.168.1.50
    raspberry_pis:
      hosts:
        giro:
          ansible_host: giro.thesniderpad.com
          ansible_user: administrator
    home_assistant_nodes:
      hosts:
        giro:
      vars:
        raspberry_pi_allowed_ports:
          - 8123
