# ansible-task
- name: Ensure ~/code directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/code"
    state: directory
    mode: '0755'

- name: Configure git user name
  community.general.git_config:
    name: user.name
    value: "David Snider"
    scope: global

- name: Configure git user email
  community.general.git_config:
    name: user.email
    value: "david@davidsnider.org"
    scope: global

- name: Configure git to use ssh.exe for SSH connections
  community.general.git_config:
    name: core.sshCommand
    value: "ssh.exe"
    scope: global

- name: Configure git signing key
  community.general.git_config:
    name: user.signingkey
    value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKWm36FodEyxXOXxqhkCj0YLDHkori4Dzmq3hI0PsrX9"
    scope: global

- name: Configure GPG format
  community.general.git_config:
    name: gpg.format
    value: "ssh"
    scope: global

- name: Configure GPG SSH program
  community.general.git_config:
    name: gpg.ssh.program
    value: "/mnt/c/Users/david/AppData/Local/1Password/app/8/op-ssh-sign-wsl"
    scope: global

- name: Enable commit GPG signing
  community.general.git_config:
    name: commit.gpgsign
    value: "true"
    scope: global

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.ssh"
    state: directory
    mode: '0700'

- name: Create SSH allowed signers file
  ansible.builtin.copy:
    content: "david@davidsnider.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKWm36FodEyxXOXxqhkCj0YLDHkori4Dzmq3hI0PsrX9"
    dest: "{{ lookup('env', 'HOME') }}/.ssh/allowed_signers"
    mode: '0644'

- name: Configure Git allowed signers file
  community.general.git_config:
    name: gpg.ssh.allowedSignersFile
    value: "{{ lookup('env', 'HOME') }}/.ssh/allowed_signers"
    scope: global

- name: Install a package and update cache if needed
  become: true
  ansible.builtin.apt:
    name:
      - gh
      - htop
      - jq
      - python3-poetry
      - pre-commit
      - zsh
      # - zsh-autocomplete
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - unzip
    state: present
    update_cache: true
    cache_valid_time: 86400 # in seconds, equals 24 hours

- name: Get current user
  ansible.builtin.command: whoami
  register: current_user
  changed_when: false

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ current_user.stdout }}"
    shell: /usr/bin/zsh
  become: true

- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.local/bin"
    state: directory
    mode: '0755'

- name: Install oh-my-posh if not present
  ansible.builtin.shell:
    cmd: curl -s https://ohmyposh.dev/install.sh | bash -s
  environment:
    OMP_INSTALL_DIR: "{{ lookup('env', 'HOME') }}/.local/bin"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/oh-my-posh"

- name: Check if Oh My Zsh is installed
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Remove .zprofile if it exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.zprofile"
    state: absent

- name: Install Oh My Zsh if not present
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  when: not oh_my_zsh_stat.stat.exists
  changed_when: false

- name: Copy zshrc file
  ansible.builtin.copy:
    src: zshrc-linux
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    mode: '0644'

- name: Copy zprofile file
  ansible.builtin.copy:
    src: zprofile-linux
    dest: "{{ lookup('env', 'HOME') }}/.zprofile"
    mode: '0644'

- name: Install Pulumi CLI
  block:
    - name: Check if Pulumi is already installed
      ansible.builtin.command: which pulumi
      register: pulumi_check
      failed_when: false
      changed_when: false

    - name: Download and install Pulumi CLI
      ansible.builtin.shell: |
        curl -fsSL https://get.pulumi.com | sh
      when: pulumi_check.rc != 0
      changed_when: true


- name: Download and install 1Password CLI
  block:
    - name: Download 1Password GPG key
      ansible.builtin.get_url:
        url: https://downloads.1password.com/linux/keys/1password.asc
        dest: /tmp/1password.asc
        mode: '0644'

    - name: Create 1Password keyring directory
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'
      become: true

    - name: Import 1Password GPG key to system keyring
      ansible.builtin.shell: |
        gpg --dearmor < /tmp/1password.asc > /usr/share/keyrings/1password-archive-keyring.gpg
      become: true

    - name: Get system architecture
      ansible.builtin.command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Add 1Password repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ system_arch.stdout }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ system_arch.stdout }} stable main"
        filename: 1password
        state: present
      become: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true

    - name: Install 1Password CLI
      ansible.builtin.apt:
        name: 1password-cli
        state: present
      become: true

  always:
    - name: Clean up temporary files
      ansible.builtin.file:
        path: /tmp/1password.asc
        state: absent
