---
- name: Include shared global Git configuration
  ansible.builtin.include_tasks: setup-git.yml

- name: Include local-mac tasks if MacOS
  ansible.builtin.include_tasks: local-mac.yml
  when: ansible_facts['system'] == 'Darwin'

- name: Include local-linux tasks if Linux
  ansible.builtin.include_tasks: local-linux.yml
  when: ansible_facts['system'] == 'Linux'

- name: Include gemini-setup tasks
  ansible.builtin.include_tasks: gemini-setup.yml
