---
- name: Converge Linux-specific test (Fast)
  hosts: localhost_linux
  gather_facts: true
  tasks:
    - name: Update apt cache (Ubuntu/Debian)
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Python pip
      become: true
      ansible.builtin.apt:
        name: python3-pip
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Create test user home directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}"
        state: directory
        mode: "0755"

    # Include the full Linux tasks to properly test 1Password security features
    - name: Include Linux-specific tasks
      ansible.builtin.include_tasks: ../../tasks/local-linux.yml
