---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: localhost-ubuntu-22-fast
    image: ansible-home-test-base:latest
    pre_build_image: true
    groups:
      - localhost_linux
    # Keep container running between tests for reuse
    keep_volumes: true
    tmpfs:
      - /tmp
      - /var/tmp

provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost-ubuntu-22-fast:
        ansible_python_interpreter: /usr/bin/python3
        # Skip heavy installations since they're pre-installed
        quick_test_mode: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      bin_ansible_callbacks: true
    ssh_connection:
      pipelining: true  # Enable pipelining for faster execution

verifier:
  name: testinfra

scenario:
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
    # Skip cleanup and destroy for container reuse
