# GitHub repository configuration defaults
github_owner: davidasnider
github_repository: ansible_home
github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"

# Repository settings
repository_settings:
  description: "Ansible configuration for home automation and system setup"
  homepage: ""
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: true
  allow_auto_merge: true
  delete_branch_on_merge: true
  vulnerability_alerts: true

# Branch protection settings
branch_protection:
  branch: main
  enforce_admins: true
  required_status_checks:
    strict: true
    contexts:
      - "Ansible Linting"
      - "Pre-commit Checks"
      - "Ansible Syntax Check"
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
    restrict_dismissals: false
  restrictions:
    push: []
    apps: []
  allow_force_pushes: false
  allow_deletions: false
  require_signed_commits: true
  require_linear_history: true
  require_conversation_resolution: true

# Security settings
security_settings:
  enable_secret_scanning: true
  enable_secret_scanning_push_protection: true
  enable_dependency_alerts: true
  enable_automated_security_fixes: true
