---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: localhost-ubuntu
    image: ubuntu:22.04
    pre_build_image: true
    privileged: false
    command: /bin/bash
    tty: true
    groups:
      - localhost_linux

provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost-ubuntu:
        ansible_python_interpreter: /usr/bin/python3
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: ansible.builtin.default
      result_format: yaml
      bin_ansible_callbacks: true
    ssh_connection:
      pipelining: false

verifier:
  name: testinfra

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
