---
- name: Detect OS and include the appropriate local playbook
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Include local-mac.yml if MacOS
      ansible.builtin.include_tasks: local-mac.yml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Include local-linux.yml if Linux
      ansible.builtin.include_tasks: local-linux.yml
      when: ansible_facts['os_family'] == 'Linux'
