---
- name: Detect OS and include the appropriate local task file  # Trigger CI
  hosts: localhost
  gather_facts: true
  vars:
    ansible_become_pass: "{{ lookup('ansible.builtin.env', 'ANSIBLE_SUDO_PASS') }}"

  tasks:
    - name: Include local-mac tasks if MacOS
      ansible.builtin.include_tasks: ../roles/localhost/tasks/local-mac.yml
      when: ansible_system == 'Darwin'

    - name: Include local-linux tasks if Linux
      ansible.builtin.include_tasks: ../roles/localhost/tasks/local-linux.yml
      when: ansible_system == 'Linux'
