---
- name: Detect OS and include the appropriate local task file
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Include local-mac tasks if MacOS
      ansible.builtin.include_tasks: ../roles/localhost/tasks/local-mac.yml
      when: ansible_system == 'Darwin'

    - name: Include local-linux tasks if Linux
      ansible.builtin.include_tasks: ../roles/localhost/tasks/local-linux.yml
      when: ansible_system == 'Linux'
