---
- name: Configure All Raspberry Pis
  hosts: raspberry_pis
  gather_facts: true
  become: true

  roles:
    - raspberry_pi

- name: Setup Home Assistant Remote Nodes
  hosts: home_assistant_nodes
  gather_facts: true
  become: true

  roles:
    - docker
    - home_assistant_remote
