name: Ansible Lint and Syntax Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run Ansible Lint
        run: ansible-lint playbooks/

      - name: Run Syntax Check
        run: |
          for playbook in playbooks/*.yml; do
            ansible-playbook --syntax-check "$playbook";
          done
