name: Branch Protection Rules

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  enforce-branch-protection:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Enforce branch protection rules
        uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require("@octokit/rest");
            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            await octokit.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "main",
              required_status_checks: {
                strict: true,
                contexts: []
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1
              },
              restrictions: null
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
