name: Molecule Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  molecule-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule[docker]

      - name: Run Molecule Tests
        run: |
          for role in roles/*; do
            if [ -d "$role/molecule" ]; then
              cd "$role" && molecule test && cd -;
            fi
          done
